[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

; Dependencias requeridas por el firmware SafeHome original.
lib_deps =
  bblanchon/ArduinoJson@^7.0.4
  ESP32Async/ESPAsyncWebServer@^3.6.0
  ESP32Async/AsyncTCP@^3.3.2
  madhephaestus/ESP32Servo@^3.0.6
  adafruit/Adafruit AHTX0@^2.0.5
  adafruit/Adafruit BMP280 Library@^2.6.8
